name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    outputs:
      artifact: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: task build

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: bruh-${{ matrix.os }}
          path: dist/bruh



